name: 'Terraform CI/CD'

on:
  push:
    branches:
      - dev
      - test
      - main
  pull_request:

jobs:
  terraform:
    name: 'Deploy Terraform to Azure'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Checkout'
    - uses: actions/checkout@v3

    - name: 'Print github.ref'
      run: echo ${GITHUB_REF##*/} 
    
    - name: 'Set up Azure credentials'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # New section to try to fix auth issue
#    - name: Login to Azure
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}

#    - name: 'Install Chckov'
#      run: pip3 install checkov

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
#      with:
#        terraform_version: 1.7.5
#        cli_config_credentials_token: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Set up Azure credentials'
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
      
    #- name: 'Terraform Init'
    #  run: terraform init -backend-config=key=prod-terraform.tfstate
    # Adding three stages
    - name: 'Terraform Init'
      run: terraform init -backend-config=key=${{ github.ref == 'refs/heads/main' && 'prod' || (github.ref == 'refs/heads/test' && 'test' || 'dev') }}-terraform.tfstate
    #Adding logic to determine issues with ranch selection
    #  run: |
    #    key=${{ github.ref == 'refs/heads/main' && 'prod' || (github.ref == 'refs/heads/test' && 'test' || 'dev') }}
    #    echo "key: $key"
    #    terraform init -backend-config=key=$key-terraform.tfstate


    # Checks that all Terraform configuration files adhere to a canonical format
    #- name: Terraform Format
    #  run: terraform fmt -check
    - name: 'Terraform Validate'
      run: terraform validate

    #- name: 'Terraform Plan'
    #  #run: terraform plan -var-file="./prod.tfvars"
    #  run: terraform plan -var-file=./${{ github.ref == 'refs/heads/main' && 'prod' || (github.ref == 'refs/heads/test' && 'test' || 'dev') }}.tfvars
    - name: 'Terraform Plan'
      run: |
        var_file=./${{ github.ref == 'refs/heads/main' && 'prod' || (github.ref == 'refs/heads/test' && 'test' || 'dev') }}.tfvars
        echo "var_file: $var_file"
        terraform plan -var-file=$var_file


    # Run Checkov against configuration
#    - name: Checkov
#      #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#      if: github.event_name == 'pull_request'
#      id: checkov
#      uses: bridgecrewio/checkov-action@master
#      with:
#        quiet: true
#        framework: terraform
#        container_user: 1000
#        output_format: github_failed_only
#        soft_fail: false
#        skip_path: /remote_state
#        skip_check: CKV_AZURE_88,CKV_AZURE_71,CKV_AZURE_16,CKV_AZURE_80,CKV_AZURE_63,CKV_AZURE_18,CKV_AZURE_65,CKV_AZURE_17,CKV_AZURE_13,CKV_AZURE_78,CKV_AZURE_66,CKV_AZURE_44,CKV_AZURE_35,CKV_AZURE_43,CKV_AZURE_33,CKV_AZURE_3,CKV2_AZURE_1,CKV2_AZURE_18,CKV2_AZURE_8,CKV2_AZURE_21,CKV_GIT_4,CKV2_AZURE_33
    
        # Add a comment to pull requests with plan results
    - name: 'Terraform Apply'
      if: github.event_name == 'push' && (github.ref == 'refs/heads/test' || github.ref == 'refs/heads/main')
      run: terraform apply -var-file="${{ github.ref == 'refs/heads/main' && './prod.tfvars' || './test.tfvars' }}" -auto-approve
#    - name: 'Terraform Apply'
#      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#      run: terraform apply -var-file="./prod.tfvars" -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
